#include "phu_fw_offsets.h"

#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include <sys/sysctl.h>

extern int klog_printf(const char *fmt, ...);

// Firmware offsets table — 41 entries (fw 3.00 -> 12.00)
// allproc + sysentvec : imported from EchoStretch/kstuff-lite prosper0gdb/offsets/
// 5.x has vm_map_pmap=0x1D0, 6.x+ has 0x1D8 (extractor-validated 8 fws)

static const phu_fw_offsets_t g_fw_table[] = {

    {
        .fw_label              = "10.00",
        .sdk_version_min       = 0x10000000,
        .sdk_version_max       = 0x1000ffff,
        .kbase_allproc         = 0x2765d70,
        .kbase_sysentvec       = 0xdba6d8,
        .kbase_sysentvec_ps4   = 0xdba850,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "10.01",
        .sdk_version_min       = 0x10010000,
        .sdk_version_max       = 0x1001ffff,
        .kbase_allproc         = 0x2765d70,
        .kbase_sysentvec       = 0xdba6d8,
        .kbase_sysentvec_ps4   = 0xdba850,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "10.20",
        .sdk_version_min       = 0x10200000,
        .sdk_version_max       = 0x1020ffff,
        .kbase_allproc         = 0x2765d70,
        .kbase_sysentvec       = 0xdba6d8,
        .kbase_sysentvec_ps4   = 0xdba850,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "10.40",
        .sdk_version_min       = 0x10400000,
        .sdk_version_max       = 0x1040ffff,
        .kbase_allproc         = 0x2765d70,
        .kbase_sysentvec       = 0xdba6d8,
        .kbase_sysentvec_ps4   = 0xdba850,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "10.60",
        .sdk_version_min       = 0x10600000,
        .sdk_version_max       = 0x1060ffff,
        .kbase_allproc         = 0x2765d70,
        .kbase_sysentvec       = 0xdba6d8,
        .kbase_sysentvec_ps4   = 0xdba850,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "11.00",
        .sdk_version_min       = 0x11000000,
        .sdk_version_max       = 0x1100ffff,
        .kbase_allproc         = 0x2875d70,
        .kbase_sysentvec       = 0xdcbc78,
        .kbase_sysentvec_ps4   = 0xdcbdf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "11.20",
        .sdk_version_min       = 0x11200000,
        .sdk_version_max       = 0x1120ffff,
        .kbase_allproc         = 0x2875d70,
        .kbase_sysentvec       = 0xdcbc78,
        .kbase_sysentvec_ps4   = 0xdcbdf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "11.40",
        .sdk_version_min       = 0x11400000,
        .sdk_version_max       = 0x1140ffff,
        .kbase_allproc         = 0x2875d70,
        .kbase_sysentvec       = 0xdcbc98,
        .kbase_sysentvec_ps4   = 0xdcbe10,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "11.60",
        .sdk_version_min       = 0x11600000,
        .sdk_version_max       = 0x1160ffff,
        .kbase_allproc         = 0x2875d70,
        .kbase_sysentvec       = 0xdcbc98,
        .kbase_sysentvec_ps4   = 0xdcbe10,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "12.00",
        .sdk_version_min       = 0x12000000,
        .sdk_version_max       = 0x1200ffff,
        .kbase_allproc         = 0x2885e00,
        .kbase_sysentvec       = 0xdcc978,
        .kbase_sysentvec_ps4   = 0xdccaf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    /* r19.67 — fws 12.02 / 12.20 / 12.40 / 12.60 / 12.70 added from kstuff-lite v1.05.
     * All 5 fws have IDENTICAL kstuff offsets to 12.00 (= verified via prosper0gdb/offsets/12_*.h
     * 2026-05-22). Struct offsets (proc/vm_map/pmap) inherited from 12.00 family. */
    {
        .fw_label              = "12.02",
        .sdk_version_min       = 0x12020000,
        .sdk_version_max       = 0x1202ffff,
        .kbase_allproc         = 0x2885e00,
        .kbase_sysentvec       = 0xdcc978,
        .kbase_sysentvec_ps4   = 0xdccaf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "12.20",
        .sdk_version_min       = 0x12200000,
        .sdk_version_max       = 0x1220ffff,
        .kbase_allproc         = 0x2885e00,
        .kbase_sysentvec       = 0xdcc978,
        .kbase_sysentvec_ps4   = 0xdccaf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "12.40",
        .sdk_version_min       = 0x12400000,
        .sdk_version_max       = 0x1240ffff,
        .kbase_allproc         = 0x2885e00,
        .kbase_sysentvec       = 0xdcc978,
        .kbase_sysentvec_ps4   = 0xdccaf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "12.60",
        .sdk_version_min       = 0x12600000,
        .sdk_version_max       = 0x1260ffff,
        .kbase_allproc         = 0x2885e00,
        .kbase_sysentvec       = 0xdcc978,
        .kbase_sysentvec_ps4   = 0xdccaf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "12.70",
        .sdk_version_min       = 0x12700000,
        .sdk_version_max       = 0x1270ffff,
        .kbase_allproc         = 0x2885e00,
        .kbase_sysentvec       = 0xdcc978,
        .kbase_sysentvec_ps4   = 0xdccaf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "3.00",
        .sdk_version_min       = 0x03000000,
        .sdk_version_max       = 0x0300ffff,
        .kbase_allproc         = 0x276dc58,
        .kbase_sysentvec       = 0xca0cd8,
        .kbase_sysentvec_ps4   = 0xca0e50,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "3.10",
        .sdk_version_min       = 0x03100000,
        .sdk_version_max       = 0x0310ffff,
        .kbase_allproc         = 0x276dc58,
        .kbase_sysentvec       = 0xca0cd8,
        .kbase_sysentvec_ps4   = 0xca0e50,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "3.20",
        .sdk_version_min       = 0x03200000,
        .sdk_version_max       = 0x0320ffff,
        .kbase_allproc         = 0x276dc58,
        .kbase_sysentvec       = 0xca0cd8,
        .kbase_sysentvec_ps4   = 0xca0e50,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "3.21",
        .sdk_version_min       = 0x03210000,
        .sdk_version_max       = 0x0321ffff,
        .kbase_allproc         = 0x276dc58,
        .kbase_sysentvec       = 0xca0cd8,
        .kbase_sysentvec_ps4   = 0xca0e50,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "4.00",
        .sdk_version_min       = 0x04000000,
        .sdk_version_max       = 0x0400ffff,
        .kbase_allproc         = 0x27edcb8,
        .kbase_sysentvec       = 0xd11bb8,
        .kbase_sysentvec_ps4   = 0xd11d30,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "4.02",
        .sdk_version_min       = 0x04020000,
        .sdk_version_max       = 0x0402ffff,
        .kbase_allproc         = 0x27edcb8,
        .kbase_sysentvec       = 0xd11bb8,
        .kbase_sysentvec_ps4   = 0xd11d30,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "4.03",
        .sdk_version_min       = 0x04030000,
        .sdk_version_max       = 0x0403ffff,
        .kbase_allproc         = 0x27edcb8,
        .kbase_sysentvec       = 0xd11bb8,
        .kbase_sysentvec_ps4   = 0xd11d30,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "4.50",
        .sdk_version_min       = 0x04500000,
        .sdk_version_max       = 0x0450ffff,
        .kbase_allproc         = 0x27edcb8,
        .kbase_sysentvec       = 0xd11bb8,
        .kbase_sysentvec_ps4   = 0xd11d30,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "4.51",
        .sdk_version_min       = 0x04510000,
        .sdk_version_max       = 0x0451ffff,
        .kbase_allproc         = 0x27edcb8,
        .kbase_sysentvec       = 0xd11bb8,
        .kbase_sysentvec_ps4   = 0xd11d30,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "5.00",
        .sdk_version_min       = 0x05000000,
        .sdk_version_max       = 0x0500ffff,
        .kbase_allproc         = 0x291dd00,
        .kbase_sysentvec       = 0xe00be8,
        .kbase_sysentvec_ps4   = 0xe00d60,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "5.02",
        .sdk_version_min       = 0x05020000,
        .sdk_version_max       = 0x0502ffff,
        .kbase_allproc         = 0x291dd00,
        .kbase_sysentvec       = 0xe00be8,
        .kbase_sysentvec_ps4   = 0xe00d60,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "5.10",
        .sdk_version_min       = 0x05100000,
        .sdk_version_max       = 0x0510ffff,
        .kbase_allproc         = 0x291dd00,
        .kbase_sysentvec       = 0xe00be8,
        .kbase_sysentvec_ps4   = 0xe00d60,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        // v1.12.4 : empirical fix from PHU FW Extractor dump 2026-04-26.
        // vmspace+0x1D0 on 5.10 is a list_head self-ref (vmspace+0x2e0),
        // canonical-looking but NOT a pmap -> DMAP base derivation reads
        // pm_cr3=0 -> writes to physical 0 -> SIGSEGV Mono runtime.
        // Real vm_map_pmap on fw 5.10 = +0x1C8.
        .vm_map_root           = 0x1C0,  // shifted -0x8 vs other 5.x
        .vm_map_pmap           = 0x1C8,  // empirical fw 5.10
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "5.50",
        .sdk_version_min       = 0x05500000,
        .sdk_version_max       = 0x0550ffff,
        .kbase_allproc         = 0x291dd00,
        .kbase_sysentvec       = 0xe00be8,
        .kbase_sysentvec_ps4   = 0xe00d60,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1C8,  // 5.x layout
        .vm_map_pmap           = 0x1D0,  // 5.x layout
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "6.00",
        .sdk_version_min       = 0x06000000,
        .sdk_version_max       = 0x0600ffff,
        .kbase_allproc         = 0x2869d20,
        .kbase_sysentvec       = 0xe210a8,
        .kbase_sysentvec_ps4   = 0xe21220,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "6.02",
        .sdk_version_min       = 0x06020000,
        .sdk_version_max       = 0x0602ffff,
        .kbase_allproc         = 0x2869d20,
        .kbase_sysentvec       = 0xe210a8,
        .kbase_sysentvec_ps4   = 0xe21220,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "6.50",
        .sdk_version_min       = 0x06500000,
        .sdk_version_max       = 0x0650ffff,
        .kbase_allproc         = 0x2869d20,
        .kbase_sysentvec       = 0xe210a8,
        .kbase_sysentvec_ps4   = 0xe21220,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "7.00",
        .sdk_version_min       = 0x07000000,
        .sdk_version_max       = 0x0700ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21ab8,
        .kbase_sysentvec_ps4   = 0xe21c30,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "7.01",
        .sdk_version_min       = 0x07010000,
        .sdk_version_max       = 0x0701ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21ab8,
        .kbase_sysentvec_ps4   = 0xe21c30,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "7.20",
        .sdk_version_min       = 0x07200000,
        .sdk_version_max       = 0x0720ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21b78,
        .kbase_sysentvec_ps4   = 0xe21cf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "7.40",
        .sdk_version_min       = 0x07400000,
        .sdk_version_max       = 0x0740ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21b78,
        .kbase_sysentvec_ps4   = 0xe21cf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "7.60",
        .sdk_version_min       = 0x07600000,
        .sdk_version_max       = 0x0760ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21b78,
        .kbase_sysentvec_ps4   = 0xe21cf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    /* r19.70 — fw 7.20 added (= 7.xx era pre-Cronos hybrid, kstuff offsets identical to 7.40/7.60/7.61). */
    {
        .fw_label              = "7.20",
        .sdk_version_min       = 0x07200000,
        .sdk_version_max       = 0x0720ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21b78,
        .kbase_sysentvec_ps4   = 0xe21cf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    /* r19.69 — fw 7.40 added (= 7.xx era pre-Cronos hybrid, kstuff offsets identical to 7.60/7.61). */
    {
        .fw_label              = "7.40",
        .sdk_version_min       = 0x07400000,
        .sdk_version_max       = 0x0740ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21b78,
        .kbase_sysentvec_ps4   = 0xe21cf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "7.61",
        .sdk_version_min       = 0x07610000,
        .sdk_version_max       = 0x0761ffff,
        .kbase_allproc         = 0x2859d50,
        .kbase_sysentvec       = 0xe21b78,
        .kbase_sysentvec_ps4   = 0xe21cf0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "8.00",
        .sdk_version_min       = 0x08000000,
        .sdk_version_max       = 0x0800ffff,
        .kbase_allproc         = 0x2875d50,
        .kbase_sysentvec       = 0xe21ca8,
        .kbase_sysentvec_ps4   = 0xe21e20,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "8.20",
        .sdk_version_min       = 0x08200000,
        .sdk_version_max       = 0x0820ffff,
        .kbase_allproc         = 0x2875d50,
        .kbase_sysentvec       = 0xe21ca8,
        .kbase_sysentvec_ps4   = 0xe21e20,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "8.40",
        .sdk_version_min       = 0x08400000,
        .sdk_version_max       = 0x0840ffff,
        .kbase_allproc         = 0x2875d50,
        .kbase_sysentvec       = 0xe21ca8,
        .kbase_sysentvec_ps4   = 0xe21e20,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "8.60",
        .sdk_version_min       = 0x08600000,
        .sdk_version_max       = 0x0860ffff,
        .kbase_allproc         = 0x2875d50,
        .kbase_sysentvec       = 0xe21ca8,
        .kbase_sysentvec_ps4   = 0xe21e20,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0ULL,
    },
    {
        .fw_label              = "9.00",
        .sdk_version_min       = 0x09000000,
        .sdk_version_max       = 0x0900ffff,
        .kbase_allproc         = 0x2755d50,
        .kbase_sysentvec       = 0xdba648,
        .kbase_sysentvec_ps4   = 0xdba7c0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0xffff873b00000000ULL,  // 9.x empirical (validated 9.40)
    },
    {
        .fw_label              = "9.05",
        .sdk_version_min       = 0x09050000,
        .sdk_version_max       = 0x0905ffff,
        .kbase_allproc         = 0x2755d50,
        .kbase_sysentvec       = 0xdba648,
        .kbase_sysentvec_ps4   = 0xdba7c0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0xffff873b00000000ULL,  // 9.x empirical (validated 9.40)
    },
    {
        .fw_label              = "9.20",
        .sdk_version_min       = 0x09200000,
        .sdk_version_max       = 0x0920ffff,
        .kbase_allproc         = 0x2755d50,
        .kbase_sysentvec       = 0xdba648,
        .kbase_sysentvec_ps4   = 0xdba7c0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0xffff873b00000000ULL,  // 9.x empirical (validated 9.40)
    },
    {
        .fw_label              = "9.40",
        .sdk_version_min       = 0x09400000,
        .sdk_version_max       = 0x0940ffff,
        .kbase_allproc         = 0x2755d50,
        .kbase_sysentvec       = 0xdba648,
        .kbase_sysentvec_ps4   = 0xdba7c0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,  // p_list.le_next = first field of struct proc
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0xffff873b00000000ULL,  // 9.40 empirical (validated dev baseline)
    },
    {
        .fw_label              = "9.60",
        .sdk_version_min       = 0x09600000,
        .sdk_version_max       = 0x0960ffff,
        .kbase_allproc         = 0x2755d50,
        .kbase_sysentvec       = 0xdba648,
        .kbase_sysentvec_ps4   = 0xdba7c0,
        .proc_p_pid            = 0xBC,
        .proc_p_vmspace        = 0x200,
        .proc_titleid          = 0x470,
        .proc_p_next           = 0x0,
        .vm_map_root           = 0x1D0,
        .vm_map_pmap           = 0x1D8,
        .vm_map_sentinel_next  = 0x8,
        .pmap_pm_pml4          = 0x20,
        .pmap_pm_cr3           = 0x28,
        .vme_start             = 0x20,
        .vme_end               = 0x28,
        .vme_protection        = 0x64,
        .vme_max_protection    = 0x66,
        .vme_next              = 0x8,
        .dmap_base_fallback    = 0xffff873b00000000ULL,  // 9.x empirical (validated 9.40); PS5 Pro same SDK shares entry
    },
};

static const size_t g_fw_table_len = sizeof(g_fw_table) / sizeof(g_fw_table[0]);

static const phu_fw_offsets_t *g_current_entry = NULL;
static uint32_t                g_current_sdk   = 0;
static int                     g_current_cached = 0;

uint32_t phu_fw_get_current_sdk_version(void) {
    uint32_t sdk = 0; size_t sdk_sz = sizeof(sdk);
    if (sysctlbyname("kern.sdk_version", &sdk, &sdk_sz, NULL, 0) != 0) return 0;
    return sdk;
}

const phu_fw_offsets_t *phu_fw_offsets_lookup(uint32_t sdk_version) {
    for (size_t i = 0; i < g_fw_table_len; i++) {
        const phu_fw_offsets_t *e = &g_fw_table[i];
        if (sdk_version >= e->sdk_version_min && sdk_version <= e->sdk_version_max)
            return e;
    }
    return NULL;
}

/* v1.12.5 : when the table entry has kbase_sysentvec_ps4==0 (11.x / 12.x
 * not yet in etaHEN msg.cpp table), apply the empirical +0x178 delta
 * observed on every fw 3.00 → 10.01. This unblocks PS4 BC kstuff handshake
 * (pause_resume_kstuff must flip BOTH sysentvecs ; skipping PS4 = panic
 * on PS4-path syscalls like sceNotificationSend on BC titles). The
 * +0x178 pattern is stable across 8+ validated fws ; risk of regression
 * is lower than the crash from skipping PS4 entirely. */
static phu_fw_offsets_t g_current_entry_storage;

const phu_fw_offsets_t *phu_fw_offsets_current(void) {
    if (g_current_cached) return g_current_entry;
    g_current_sdk = phu_fw_get_current_sdk_version();
    const phu_fw_offsets_t *base = phu_fw_offsets_lookup(g_current_sdk);
    if (base && base->kbase_sysentvec_ps4 == 0 && base->kbase_sysentvec != 0) {
        g_current_entry_storage = *base;
        g_current_entry_storage.kbase_sysentvec_ps4 =
            base->kbase_sysentvec + 0x178;
        klog_printf("[phu_fw] sysentvec_ps4 fallback : %s = 0x%lx (sysentvec+0x178)\n",
                    base->fw_label,
                    (unsigned long)g_current_entry_storage.kbase_sysentvec_ps4);
        g_current_entry = &g_current_entry_storage;
    } else {
        g_current_entry = base;
    }
    g_current_cached = 1;
    return g_current_entry;
}

extern void phu_diag_log(const char *fmt, ...) __attribute__((format(printf, 1, 2)));

void phu_fw_offsets_log_current(void) {
    uint32_t sdk = phu_fw_get_current_sdk_version();
    const phu_fw_offsets_t *e = phu_fw_offsets_lookup(sdk);
    if (!e) {
        klog_printf("[phu_fw] UNSUPPORTED sdk=0x%08x fw %x.%02x no entry\n",
                    sdk, (sdk >> 24) & 0xFF, (sdk >> 16) & 0xFF);
        phu_diag_log("FW DETECT : UNSUPPORTED sdk=0x%08x fw %x.%02x — no offsets entry, kstuff handshake disabled",
                     sdk, (sdk >> 24) & 0xFF, (sdk >> 16) & 0xFF);
        return;
    }
    klog_printf("[phu_fw] fw=%s sdk=0x%08x allproc=0x%lx sysentvec=0x%lx sysentvec_ps4=0x%lx\n",
                e->fw_label, sdk,
                (unsigned long)e->kbase_allproc,
                (unsigned long)e->kbase_sysentvec,
                (unsigned long)e->kbase_sysentvec_ps4);
    phu_diag_log("FW DETECT : fw=%s sdk=0x%08x allproc=0x%lx sysentvec=0x%lx sysentvec_ps4=0x%lx",
                 e->fw_label, sdk,
                 (unsigned long)e->kbase_allproc,
                 (unsigned long)e->kbase_sysentvec,
                 (unsigned long)e->kbase_sysentvec_ps4);
}
